sudo: required
dist: trusty
language: generic
install:
      - if \[ "$TOXENV" == "py35" \]; then sudo apt-get -qq update ; sudo apt-get install -y python3 ; fi
      - sudo pip install -U pip tox
script:
      - tox
env:
      - TOXENV=py27
      - TOXENV=py35
      - TOXENV=pep8
      - TOXENV=docs
