sudo: required
dist: trusty
language: generic
install:
      - if \[ "$TOXENV" == "py36" \]; then sudo add-apt-repository -y ppa:deadsnakes/ppa ; sudo apt-get -qq update ; sudo apt-get install -y python3.6 python3.6-dev; fi
      - sudo pip install -U pip tox
script:
      - tox
env:
      - TOXENV=py27
      - TOXENV=py36
      - TOXENV=pep8
      - TOXENV=docs
