sudo: true
language: generic
install:
      - [ "$TOXENV" == "py35" ] && sudo apt-get -qq update && sudo apt-get install -y python3
      - sudo pip install -U pip tox
script:
      - tox
env:
      - TOXENV=py27
      - TOXENV=py35
      - TOXENV=pep8
      - TOXENV=docs
